### ISSUE TITLE
Error creating shader at com.google.ar.core.codelab.common.rendering.ShaderUtil.loadGLShader(ShaderUtil.java:53)

### ISSUE THREAD

**Issue by agGitHub** [google-ar/codelab-raw-depth-api#1]
Hi,

When trying to run samples 2 and 3, I get the following error:

```
2021-05-27 16:38:48.698 17037-18105/com.google.ar.core.codelab.rawdepth E/AndroidRuntime: FATAL EXCEPTION: GLThread 12755
    Process: com.google.ar.core.codelab.rawdepth, PID: 17037
    java.lang.RuntimeException: Error creating shader.
        at com.google.ar.core.codelab.common.rendering.ShaderUtil.loadGLShader(ShaderUtil.java:53)
        at com.google.ar.core.codelab.common.rendering.DepthRenderer.createOnGlThread(DepthRenderer.java:67)
        at com.google.ar.core.codelab.rawdepth.RawDepthCodelabActivity.onSurfaceCreated(RawDepthCodelabActivity.java:208)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1559)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

Any idea how to solve it ?

Thanks.

**Comment by nadiawangberg** [comment]
Did you manage to solve this?

**Comment by mcallistertyler** [comment]
Hi,

I was able to solve this by changing the following lines in _depth_point_cloud.vert_ from:
```
   float kMinHeightMeters = -2.0f;
   float kMaxHeightMeters = 2.0f;
```
to:
```
   float kMinHeightMeters = -2.0;
   float kMaxHeightMeters = 2.0;
```
